/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ControlCenterRouteImport } from './routes/control-center'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutHnchatRouteImport } from './routes/about-hnchat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as AdminVisitsRouteImport } from './routes/admin.visits'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminProjectCommandsRouteImport } from './routes/admin.project-commands'
import { Route as AdminManageRouteImport } from './routes/admin.manage'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminHnchatKitRouteImport } from './routes/admin.hnchat-kit'
import { Route as AdminGithubSyncRouteImport } from './routes/admin.github-sync'
import { Route as AdminControlHubRouteImport } from './routes/admin.control-hub'
import { Route as AdminControlCenterRouteImport } from './routes/admin.control-center'
import { Route as AdminChecksRouteImport } from './routes/admin.checks'
import { Route as AdminAnalyticsHubRouteImport } from './routes/admin.analytics-hub'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminAdsenseKitRouteImport } from './routes/admin.adsense-kit'
import { Route as ApiPublicCronCheckProjectsRouteImport } from './routes/api.public.cron.check-projects'
import { Route as ApiPublicCronCheckLovableRouteImport } from './routes/api.public.cron.check-lovable'
import { Route as ApiPublicControlSyncSiteRouteImport } from './routes/api.public.control.sync-site'
import { Route as ApiPublicControlHealthCheckRouteImport } from './routes/api.public.control.health-check'
import { Route as ApiPublicAnalyticsTrackRouteImport } from './routes/api.public.analytics.track'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterRoute = ControlCenterRouteImport.update({
  id: '/control-center',
  path: '/control-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHnchatRoute = AboutHnchatRouteImport.update({
  id: '/about-hnchat',
  path: '/about-hnchat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AdminVisitsRoute = AdminVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectCommandsRoute = AdminProjectCommandsRouteImport.update({
  id: '/project-commands',
  path: '/project-commands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageRoute = AdminManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHnchatKitRoute = AdminHnchatKitRouteImport.update({
  id: '/hnchat-kit',
  path: '/hnchat-kit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGithubSyncRoute = AdminGithubSyncRouteImport.update({
  id: '/github-sync',
  path: '/github-sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminControlHubRoute = AdminControlHubRouteImport.update({
  id: '/control-hub',
  path: '/control-hub',
  getParentRoute: () => AdminRoute,
} as any)
const AdminControlCenterRoute = AdminControlCenterRouteImport.update({
  id: '/control-center',
  path: '/control-center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChecksRoute = AdminChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsHubRoute = AdminAnalyticsHubRouteImport.update({
  id: '/analytics-hub',
  path: '/analytics-hub',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsenseKitRoute = AdminAdsenseKitRouteImport.update({
  id: '/adsense-kit',
  path: '/adsense-kit',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCronCheckProjectsRoute =
  ApiPublicCronCheckProjectsRouteImport.update({
    id: '/api/public/cron/check-projects',
    path: '/api/public/cron/check-projects',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCheckLovableRoute =
  ApiPublicCronCheckLovableRouteImport.update({
    id: '/api/public/cron/check-lovable',
    path: '/api/public/cron/check-lovable',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicControlSyncSiteRoute =
  ApiPublicControlSyncSiteRouteImport.update({
    id: '/api/public/control/sync-site',
    path: '/api/public/control/sync-site',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicControlHealthCheckRoute =
  ApiPublicControlHealthCheckRouteImport.update({
    id: '/api/public/control/health-check',
    path: '/api/public/control/health-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAnalyticsTrackRoute = ApiPublicAnalyticsTrackRouteImport.update({
  id: '/api/public/analytics/track',
  path: '/api/public/analytics/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-hnchat': typeof AboutHnchatRoute
  '/admin': typeof AdminRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/control-center': typeof ControlCenterRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/monitor': typeof MonitorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/adsense-kit': typeof AdminAdsenseKitRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics-hub': typeof AdminAnalyticsHubRoute
  '/admin/checks': typeof AdminChecksRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/control-hub': typeof AdminControlHubRoute
  '/admin/github-sync': typeof AdminGithubSyncRoute
  '/admin/hnchat-kit': typeof AdminHnchatKitRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/project-commands': typeof AdminProjectCommandsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/analytics/track': typeof ApiPublicAnalyticsTrackRoute
  '/api/public/control/health-check': typeof ApiPublicControlHealthCheckRoute
  '/api/public/control/sync-site': typeof ApiPublicControlSyncSiteRoute
  '/api/public/cron/check-lovable': typeof ApiPublicCronCheckLovableRoute
  '/api/public/cron/check-projects': typeof ApiPublicCronCheckProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-hnchat': typeof AboutHnchatRoute
  '/admin': typeof AdminRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/control-center': typeof ControlCenterRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/monitor': typeof MonitorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/adsense-kit': typeof AdminAdsenseKitRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics-hub': typeof AdminAnalyticsHubRoute
  '/admin/checks': typeof AdminChecksRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/control-hub': typeof AdminControlHubRoute
  '/admin/github-sync': typeof AdminGithubSyncRoute
  '/admin/hnchat-kit': typeof AdminHnchatKitRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/project-commands': typeof AdminProjectCommandsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/analytics/track': typeof ApiPublicAnalyticsTrackRoute
  '/api/public/control/health-check': typeof ApiPublicControlHealthCheckRoute
  '/api/public/control/sync-site': typeof ApiPublicControlSyncSiteRoute
  '/api/public/cron/check-lovable': typeof ApiPublicCronCheckLovableRoute
  '/api/public/cron/check-projects': typeof ApiPublicCronCheckProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-hnchat': typeof AboutHnchatRoute
  '/admin': typeof AdminRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/control-center': typeof ControlCenterRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/monitor': typeof MonitorRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/refund': typeof RefundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/adsense-kit': typeof AdminAdsenseKitRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics-hub': typeof AdminAnalyticsHubRoute
  '/admin/checks': typeof AdminChecksRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/control-hub': typeof AdminControlHubRoute
  '/admin/github-sync': typeof AdminGithubSyncRoute
  '/admin/hnchat-kit': typeof AdminHnchatKitRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/project-commands': typeof AdminProjectCommandsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/analytics/track': typeof ApiPublicAnalyticsTrackRoute
  '/api/public/control/health-check': typeof ApiPublicControlHealthCheckRoute
  '/api/public/control/sync-site': typeof ApiPublicControlSyncSiteRoute
  '/api/public/cron/check-lovable': typeof ApiPublicCronCheckLovableRoute
  '/api/public/cron/check-projects': typeof ApiPublicCronCheckProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-hnchat'
    | '/admin'
    | '/community-guidelines'
    | '/contact'
    | '/control-center'
    | '/dashboard'
    | '/login'
    | '/marketplace'
    | '/monitor'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/refund'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/adsense-kit'
    | '/admin/alerts'
    | '/admin/analytics-hub'
    | '/admin/checks'
    | '/admin/control-center'
    | '/admin/control-hub'
    | '/admin/github-sync'
    | '/admin/hnchat-kit'
    | '/admin/leads'
    | '/admin/manage'
    | '/admin/project-commands'
    | '/admin/projects'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/visits'
    | '/marketplace/$slug'
    | '/projects/$slug'
    | '/api/public/analytics/track'
    | '/api/public/control/health-check'
    | '/api/public/control/sync-site'
    | '/api/public/cron/check-lovable'
    | '/api/public/cron/check-projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-hnchat'
    | '/admin'
    | '/community-guidelines'
    | '/contact'
    | '/control-center'
    | '/dashboard'
    | '/login'
    | '/marketplace'
    | '/monitor'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/refund'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/adsense-kit'
    | '/admin/alerts'
    | '/admin/analytics-hub'
    | '/admin/checks'
    | '/admin/control-center'
    | '/admin/control-hub'
    | '/admin/github-sync'
    | '/admin/hnchat-kit'
    | '/admin/leads'
    | '/admin/manage'
    | '/admin/project-commands'
    | '/admin/projects'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/visits'
    | '/marketplace/$slug'
    | '/projects/$slug'
    | '/api/public/analytics/track'
    | '/api/public/control/health-check'
    | '/api/public/control/sync-site'
    | '/api/public/cron/check-lovable'
    | '/api/public/cron/check-projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-hnchat'
    | '/admin'
    | '/community-guidelines'
    | '/contact'
    | '/control-center'
    | '/dashboard'
    | '/login'
    | '/marketplace'
    | '/monitor'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/refund'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/adsense-kit'
    | '/admin/alerts'
    | '/admin/analytics-hub'
    | '/admin/checks'
    | '/admin/control-center'
    | '/admin/control-hub'
    | '/admin/github-sync'
    | '/admin/hnchat-kit'
    | '/admin/leads'
    | '/admin/manage'
    | '/admin/project-commands'
    | '/admin/projects'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/visits'
    | '/marketplace/$slug'
    | '/projects/$slug'
    | '/api/public/analytics/track'
    | '/api/public/control/health-check'
    | '/api/public/control/sync-site'
    | '/api/public/cron/check-lovable'
    | '/api/public/cron/check-projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutHnchatRoute: typeof AboutHnchatRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ContactRoute: typeof ContactRoute
  ControlCenterRoute: typeof ControlCenterRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  MonitorRoute: typeof MonitorRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RefundRoute: typeof RefundRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicAnalyticsTrackRoute: typeof ApiPublicAnalyticsTrackRoute
  ApiPublicControlHealthCheckRoute: typeof ApiPublicControlHealthCheckRoute
  ApiPublicControlSyncSiteRoute: typeof ApiPublicControlSyncSiteRoute
  ApiPublicCronCheckLovableRoute: typeof ApiPublicCronCheckLovableRoute
  ApiPublicCronCheckProjectsRoute: typeof ApiPublicCronCheckProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center': {
      id: '/control-center'
      path: '/control-center'
      fullPath: '/control-center'
      preLoaderRoute: typeof ControlCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-hnchat': {
      id: '/about-hnchat'
      path: '/about-hnchat'
      fullPath: '/about-hnchat'
      preLoaderRoute: typeof AboutHnchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/admin/visits': {
      id: '/admin/visits'
      path: '/visits'
      fullPath: '/admin/visits'
      preLoaderRoute: typeof AdminVisitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/project-commands': {
      id: '/admin/project-commands'
      path: '/project-commands'
      fullPath: '/admin/project-commands'
      preLoaderRoute: typeof AdminProjectCommandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage': {
      id: '/admin/manage'
      path: '/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AdminManageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hnchat-kit': {
      id: '/admin/hnchat-kit'
      path: '/hnchat-kit'
      fullPath: '/admin/hnchat-kit'
      preLoaderRoute: typeof AdminHnchatKitRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/github-sync': {
      id: '/admin/github-sync'
      path: '/github-sync'
      fullPath: '/admin/github-sync'
      preLoaderRoute: typeof AdminGithubSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/control-hub': {
      id: '/admin/control-hub'
      path: '/control-hub'
      fullPath: '/admin/control-hub'
      preLoaderRoute: typeof AdminControlHubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/control-center': {
      id: '/admin/control-center'
      path: '/control-center'
      fullPath: '/admin/control-center'
      preLoaderRoute: typeof AdminControlCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checks': {
      id: '/admin/checks'
      path: '/checks'
      fullPath: '/admin/checks'
      preLoaderRoute: typeof AdminChecksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics-hub': {
      id: '/admin/analytics-hub'
      path: '/analytics-hub'
      fullPath: '/admin/analytics-hub'
      preLoaderRoute: typeof AdminAnalyticsHubRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/adsense-kit': {
      id: '/admin/adsense-kit'
      path: '/adsense-kit'
      fullPath: '/admin/adsense-kit'
      preLoaderRoute: typeof AdminAdsenseKitRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/cron/check-projects': {
      id: '/api/public/cron/check-projects'
      path: '/api/public/cron/check-projects'
      fullPath: '/api/public/cron/check-projects'
      preLoaderRoute: typeof ApiPublicCronCheckProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/check-lovable': {
      id: '/api/public/cron/check-lovable'
      path: '/api/public/cron/check-lovable'
      fullPath: '/api/public/cron/check-lovable'
      preLoaderRoute: typeof ApiPublicCronCheckLovableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/control/sync-site': {
      id: '/api/public/control/sync-site'
      path: '/api/public/control/sync-site'
      fullPath: '/api/public/control/sync-site'
      preLoaderRoute: typeof ApiPublicControlSyncSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/control/health-check': {
      id: '/api/public/control/health-check'
      path: '/api/public/control/health-check'
      fullPath: '/api/public/control/health-check'
      preLoaderRoute: typeof ApiPublicControlHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics/track': {
      id: '/api/public/analytics/track'
      path: '/api/public/analytics/track'
      fullPath: '/api/public/analytics/track'
      preLoaderRoute: typeof ApiPublicAnalyticsTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdsenseKitRoute: typeof AdminAdsenseKitRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnalyticsHubRoute: typeof AdminAnalyticsHubRoute
  AdminChecksRoute: typeof AdminChecksRoute
  AdminControlCenterRoute: typeof AdminControlCenterRoute
  AdminControlHubRoute: typeof AdminControlHubRoute
  AdminGithubSyncRoute: typeof AdminGithubSyncRoute
  AdminHnchatKitRoute: typeof AdminHnchatKitRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminManageRoute: typeof AdminManageRoute
  AdminProjectCommandsRoute: typeof AdminProjectCommandsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVisitsRoute: typeof AdminVisitsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsenseKitRoute: AdminAdsenseKitRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnalyticsHubRoute: AdminAnalyticsHubRoute,
  AdminChecksRoute: AdminChecksRoute,
  AdminControlCenterRoute: AdminControlCenterRoute,
  AdminControlHubRoute: AdminControlHubRoute,
  AdminGithubSyncRoute: AdminGithubSyncRoute,
  AdminHnchatKitRoute: AdminHnchatKitRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminManageRoute: AdminManageRoute,
  AdminProjectCommandsRoute: AdminProjectCommandsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVisitsRoute: AdminVisitsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceSlugRoute: MarketplaceSlugRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutHnchatRoute: AboutHnchatRoute,
  AdminRoute: AdminRouteWithChildren,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ContactRoute: ContactRoute,
  ControlCenterRoute: ControlCenterRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  MonitorRoute: MonitorRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RefundRoute: RefundRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicAnalyticsTrackRoute: ApiPublicAnalyticsTrackRoute,
  ApiPublicControlHealthCheckRoute: ApiPublicControlHealthCheckRoute,
  ApiPublicControlSyncSiteRoute: ApiPublicControlSyncSiteRoute,
  ApiPublicCronCheckLovableRoute: ApiPublicCronCheckLovableRoute,
  ApiPublicCronCheckProjectsRoute: ApiPublicCronCheckProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
